### ISSUE TITLE
Not anything functionality related, but could you change the wording "have any sigils" to "bear any sigils"?

### ISSUE THREAD

**Issue by OwenCMYK** [delete-44/inscryber#131]
Sorry for the incredibly minor nitpick, but Leshy never says a card has sigils. He always uses the word "Bear" and the wiki also seems to reflect this. So I just think it would be slightly more in-character (as well as more accurate to the game) if the site asked "DOES THIS CREATURE BARE ANY ***SIGILS***?"

**Comment by delete-44** [comment]
💜  Not nitpicky, this is delightful! Resolved, thanks for the suggestion
